---
- hosts: all
  become: yes
  tasks:
    - name: Update
      command: yum update

    - name: Install python3
      package:
        name: python3
        state: present

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Service
      service: 
        name: docker
        state: started

    - name: Enable Docker
      service:
        name: docker
        enabled: yes
